# R for Travis CI: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
  - main

language: r

warnings_are_errors: false

bioc_packages:
- SeqArray
- SeqVarTools
- GenomicFeatures
- TxDb.Hsapiens.UCSC.hg38.knownGene
- GENESIS

r_github_packages:
- xihaoli/STAAR
- zilinli1988/SCANG
